BASE_GERMAN_STOPWORDS = {
    "aber",
    "als",
    "also",
    "am",
    "an",
    "auch",
    "auf",
    "aus",
    "bei",
    "bin",
    "bis",
    "bist",
    "da",
    "dadurch",
    "daher",
    "darum",
    "das",
    "dass",
    "dein",
    "deine",
    "dem",
    "den",
    "der",
    "des",
    "dessen",
    "deshalb",
    "die",
    "dies",
    "dieser",
    "dieses",
    "doch",
    "dort",
    "du",
    "durch",
    "ein",
    "eine",
    "einem",
    "einen",
    "einer",
    "eines",
    "er",
    "es",
    "euer",
    "eure",
    "fur",
    "hatte",
    "hatten",
    "hattest",
    "hattet",
    "hier",
    "hinter",
    "ich",
    "ihr",
    "ihre",
    "im",
    "in",
    "ist",
    "ja",
    "jede",
    "jedem",
    "jeden",
    "jeder",
    "jedes",
    "jener",
    "jenes",
    "jetzt",
    "kann",
    "kannst",
    "konnen",
    "konnt",
    "machen",
    "mein",
    "meine",
    "mit",
    "muss",
    "musst",
    "mussen",
    "musstet",
    "nach",
    "nachdem",
    "nein",
    "nicht",
    "nun",
    "oder",
    "seid",
    "sein",
    "seine",
    "sich",
    "sie",
    "sind",
    "soll",
    "sollen",
    "sollst",
    "sollt",
    "sonst",
    "soweit",
    "sowie",
    "und",
    "unser",
    "unsere",
    "unter",
    "vom",
    "von",
    "vor",
    "wann",
    "warum",
    "was",
    "weiter",
    "weitere",
    "wenn",
    "wer",
    "werde",
    "werden",
    "werdet",
    "weshalb",
    "wie",
    "wieder",
    "wieso",
    "wir",
    "wird",
    "wirst",
    "wo",
    "woher",
    "wohin",
    "zu",
    "zum",
    "zur",
    "zwischen",
    "live", 
    "moderation"
}

PROJECT_STOPWORDS = {
    "artikel",
    "beim",
    "bild",
    "lesen",
    "mehr",
    "prozent",
    "uhr",
    "video",
    "zuvor",
}

OUTLET_STOPWORDS = {
    "antispiegel",
    "compact",
    "nius",
    "rt",
    "rtde",
    "tichy",
}


def get_german_stopwords(
    extra: list[str] | set[str] | tuple[str, ...] | None = None,
    keep: list[str] | set[str] | tuple[str, ...] | None = None,
    include_outlet_terms: bool = True,
) -> list[str]:
    """Return a project-friendly German stopword list for topic labels."""

    stopwords = set(BASE_GERMAN_STOPWORDS) | set(PROJECT_STOPWORDS)
    if include_outlet_terms:
        stopwords |= set(OUTLET_STOPWORDS)
    if extra:
        stopwords |= set(extra)
    if keep:
        stopwords -= set(keep)
    return sorted(stopwords)
